#!/bin/bash

# User defined control parameters

#====== Structure of work directories 
#
# Project/
# |   stage00.structure/
# |   |   iter00/
# |   |   |   events/
# |   |   |   |   C202411201443A/
# |   |   |   |   |   DATA/, DATABASES_MPI/, SEM/
# |   |   |   |   |   slurm/: forward.job, misfit.job, ...
# |   |   |   |   |   misfit/:   misfit.h5, grid_search.txt, ...
# |   |   |   |   |   output_forward/
# |   |   |   |   |   output_kernel/:
# |   |   |   |   |   output_perturb_dvp,dvs/: forward simulation with perturbed models (e.g. model_dvp,dvs)
# |   |   |   |   C202006211907A/
# |   |   |   |   | ...
# |   |   |   model_initial/: proc*_reg1_vpv,vph,...bin
# |   |   |   kernel_sum/: sum of event kernels (with source/receiver masks), 
# |   |   |                and reduced to specific model of anisotropy, e.g. TISO
# |   |   |   kernel_precond/: preconditioned kernel (e.g. smoothing, spatial weighting)
# |   |   |   dmodel/: search direction based on non-linear CG, and scaled to certain amplitude 
# |   |   |   model_perturb_dvp,dvs,.../: model perturbed by the (subspaces of) search direction
# |   |   |   line_search/
# |   |   |   model_updated/
#
#====== Basic workflow:
#
#   Note: [***_job] is a slurm job
#
#   [mesh_job] create mesh with initial model
#
#   for each event:
#     [forward_job] forward simulation
#     [misfit_job]  measure misfit, get adjoint source
#     [kernel_job]  kernel simulation, get model gradients (e.g. rho_, cijkl_kernel)
#
#   [kernel_mask_sum_job] sum event kernels with source/receiver masks
#   [kernel_precond_job] preconditioning with smoothing, spatial weighting, etc.
#   [dmodel_job] get search direction based on non-linear CG, and scaled to certain amplitude 
#   [model_perturb_job] perturb model parameters along some chosen search directions in dmodel (e.g. dVp, dVs)
#   [mesh_perturb_job] create meshes for perturbed models
#  
#   for each event:
#     [perturb_job] forward simulation for perturbed models
#     [search_job] grid search through a range of step lengths
#
#   [model_update_job] sum up grid search results from each event to get step length, and update model parameters
#

#====== 

# project root directory
SEM_base_dir=$(readlink -f .)

# current stage and iteration number
SEM_stage_tag=structure
SEM_stage_num=0
SEM_iter_num=0

# source dir
# use SEM_source_dir/iter??/events/<gcmtID>/misfit/CMTSOLUTION.updated
SEM_source_dir=${SEM_base_dir}/stage00_source  

# model dir at iter00
SEM_starting_model_dir=${SEM_base_dir}/mesh_initial/GLL_initial

# reference isotropic model
SEM_reference_model_dir=${SEM_base_dir}/mesh_initial/GLL_REF # proc*_reg1_[vp|vs].bin

# misfit par 
SEM_misfit_par_dir=${SEM_base_dir}/misfit_par

# approximated inverse Hessian diagonals
SEM_invhess_dir=${SEM_stage_dir}/inverse_hess/GLL # proc*_reg1_[alpha|beta|...]_invhess.bin

#====== Data directories

# specfem3d par files
SEM_config_dir=${SEM_base_dir}/sem_config  # sem_config/: DATA/Par_file, setup/constants.h.in

# specfem3d executables
SEM_build_dir=${SEM_base_dir}/build # build/bin/xmeshfem3D,xspecfem3D

# shell scripts
SEM_utils_dir=${SEM_base_dir}/sem_utils  # sem_utils/: misfit/, structure_inversion/

# event data dir
SEM_data_dir=${SEM_base_dir}/events # data_dir/<gcmtID>/STATIONS, channel.txt. CMTSOLUTION, data.h5

# stage directory 
SEM_stage_num=$(echo "$SEM_stage_num" | awk '{printf "%02d", $1}')
SEM_stage_dir=${SEM_base_dir}/stage${SEM_stage_num}_${SEM_stage_tag}

# iteration directory
SEM_iter_num=$(echo "$SEM_iter_num" | awk '{printf "%02d", $1}')
SEM_iter_dir=${SEM_stage_dir}/iter${SEM_iter_num}

# previous iteration directory
SEM_prev_iter_mum=$(echo "$SEM_iter_num" | awk '{printf "%02d", $1-1}')
SEM_prev_iter_dir=${SEM_stage_dir}/iter${SEM_prev_iter_mum}

# initial/updated model
# SEM_initial_model_dir=${SEM_prev_iter_dir}/model_updated
# if [ "$SEM_iter_num" -eq 0 ]
# then
#   SEM_initial_model_dir=${SEM_starting_model_dir}
# fi
# SEM_initial_model_dir=${SEM_iter_dir}/model_initial
# SEM_updated_model_dir=${SEM_iter_dir}/model_updated

# mesh_REF dir
#mesh_REF_dir=$base_dir/mesh_REF.stage09.iter16.polyfit_um.linfit_mtz.vp_vs_voigt

#====== slurm jobs

SEM_python_exec=python

# mpi executable
SLURM_mpiexec="srun --mpi=pmix" # SCNET
# slurm_mpiexec="mpirun -np \${SLURM_NTASKS}"

# partition config
SLURM_partition_cpu="xahcnormal" # SCNET CPU
SLURM_ncpu_per_node=64
SLURM_partition_dcu="xahdnormal" # SCNET GPU
SLURM_ndcu_per_node=4

# number of mpi processes for sem
SEM_par_file=${SEM_config_dir}/DATA/Par_file
if [ ! -f "$SEM_par_file" ]
then
    echo "[ERROR] $sem_par_file does NOT exist!"
    exit 1
fi
SEM_nproc_xi=$(grep NPROC_XI $SEM_par_file | sed 's/[^=]*=[ ]*\([0-9]*\).*/\1/')
SEM_nproc_eta=$(grep NPROC_ETA $SEM_par_file | sed 's/[^=]*=[ ]*\([0-9]*\).*/\1/')
SEM_nproc_total=$(echo $SEM_nproc_xi $SEM_nproc_eta | awk '{print $1*$2}')
SEM_num_nodes=$(echo "$SEM_nproc_total $SLURM_ndcu_per_node" | awk '{a=$1/$2}END{print (a==int(a))?a:int(a)+1}')

SLURM_args_mesh="-n ${SEM_nproc_total} -p ${SLURM_partition_cpu} -t 01:00:00" #--exclusive"

SLURM_args_forward="-N ${SEM_num_nodes} -n ${SEM_nproc_total} -p ${SLURM_partition_dcu} -t 00:30:00 --exclusive --mem=0 --gres=dcu:4" 
SLURM_args_misfit="-N 1 -n 20 -p ${SLURM_partition_cpu} -t 00:30:00"
SLURM_args_kernel="-N ${SEM_num_nodes} -n ${SEM_nproc_total} -p ${SLURM_partition_dcu} -t 01:00:00 --exclusive --mem=0 --gres=dcu:4"
SLURM_args_kernel_process=${SLURM_args_mesh}

SLURM_args_kernel_sum=${SLURM_args_mesh}
SLURM_args_kernel_precond=${SLURM_args_mesh}
SLURM_args_dmodel=${SLURM_args_mesh}
SLURM_args_model_perturb=${SLURM_args_mesh}
SLURM_args_mesh_perturb=${SLURM_args_mesh}
SLURM_args_model_update="-n 1 -p ${SLURM_partition_cpu} -t 00:30:00"

# slurm_args_kernel_convert_mask=${slurm_args_mesh}
# slurm_args_kernel_sum_smooth_precond=${slurm_args_mesh}

SLURM_args_dsyn="-N ${SEM_num_nodes} -n ${SEM_nproc_total} -p ${SLURM_partition_dcu} -t 01:00:00 --exclusive --mem=0 --gres=dcu:4"
SLURM_args_search=${SLURM_args_misfit}
SLURM_args_plot=${SLURM_args_misfit}


#====== model parameterization
SEM_parameterization_type="alpha_beta_phi_xi" # or beta_kappa_phi_xi

SEM_model_names=(alpha beta phi xi eta) # rho) # model parameters
# SEM_model_names=(beta kappa phi xi eta rho) # model parameters

# model a priori bounds
SEM_model_min_values=(-0.15 -0.15 -0.1 -0.1 0.8)
SEM_model_max_values=(0.15  0.15  0.1  0.1 1.2)
# SEM_model_min_values=(-0.1 1.7 -0.1 -0.1 0.8)
# SEM_model_max_values=(0.1  1.9  0.1  0.1 1.2)

SEM_kernel_tag="_kernel" # gradient of model parameters
SEM_dmodel_tag="_dmodel" # search direction
# SEM_model_tags=(alpha beta phi xi eta) # rho)
# SEM_kernel_tags=(alpha_kernel beta_kernel phi_kernel xi_kernel eta_kernel) # rho_kernel)
# SEM_dmodel_tags=(alpha_dmodel beta_dmodel phi_dmodel xi_dmodel eta_dmodel) # rho_dmodel)

# SEM_script_model="sem_VTI_model_in_beta_kappa_phi_xi.py"
# SEM_script_kernel="sem_VTI_kernel_in_beta_kappa_phi_xi_eta_from_cijkl_rho.py"

#====== kernel preconditioning

#--- mask around source and receiver points
# for each event e: 
#   Ke = dChi_e/dm
#   Me: masks around source and receiver points
#   He: Hessian of Chi_e, He * dm ~ Ke(m+dm) - Ke(m)
# Chi = sum(Chi_e)
# dChi/dm = sum(Ke)
# sum(Me*He, e)*dm = -1 * sum(Me*Ke, e)
# the masked Hessian diagonals are approximated by its application on a random model perturbation dm
# sum(Me*He, e)*dm = sum(Me*dKe, e), diag(sum(Me*He, e)) ~ |sum(Me*dKe, e)|
SEM_kernel_mask_source_sigma_km=50
SEM_kernel_mask_receiver_sigma_km=10

#--- clipping 
# SEM_histogram_nbin=100
# SEM_histogram_exponential_base=0.9
# SEM_cdf_threshold=0.9999

#--- smoothing
SEM_kernel_smooth_diffusion_niter=50 # iteration steps for diffusion based smoothing 
# SEM_kernel_smooth_iso_FWHM_km=10 # full width at half maximum (FWHM) of Gaussian kernel in km
# SEM_kernel_smooth_horizontal_length_km=30 # horizontal smoothing length as FWHM
# SEM_kernel_smooth_vertical_length_km=15 # vertical smoothing length as FWHM
SEM_kernel_smooth_reference_dir=${SEM_base_dir}/mesh_initial/GLL_smooth_length # in km
SEM_kernel_smooth_reference_tag=sigma # sigma = {ref_dir}/proc*_{tag}.bin
SEM_kernel_smooth_reference_scale=1  # ref_length = sigma * ref_scale
SEM_kernel_smooth_horizontal_scale=2  # horizontal smoothing length = ref_length * horizontal_scale 
SEM_kernel_smooth_vertical_scale=1 # vertical smoothing length = ref_length * vertical_scale 

#TODO: different smoothing length for different parameter classes (e.g. larger for vp, smaller for vs?)

#====== model search direction (dm)
# conjugate gradient
SEM_cg_type=HS # PR

# maximum amplitude of dmodel
SEM_dmodel_scale=0.05

#====== line search

# To account for imbalanced sensitvity between different parameter classes,
# we can seperate the search direction(dm) into two parts(dm1, dm2), for example dvp and dvs:
# and we define the new search direction is linear combination of dm1 and dm2:
#   1) dm = a1 * dm1 + a2 * dm2
# From forward modelling of models perturbed by dm1 and dm2, we can write:
#   2) du1 := u(m+dm1) - u(m) ~ dm1 * grad(u)
#   3) du2 := u(m+dm2) - u(m) ~ dm2 * grad(u)
# Synthetics from any linear combination of dm1 and dm2 can be approximated by:
#   4) u(m+dm) ~ u(m) + dm * grad(u) = u(m) + a1*dm1 * grad(u) + a2*dm2 * grad(u) ~ u(m) + a1*du1 + a2*du2
# To maximize the objective function(Chi) we grid search through a1 and a2: 
#   5) argmax(Chi[u(m)+ a1*du1 + a2*du2]) for a1,a2 in some seach ranges
# The optimal a1, a2 would give the updated model as m + a1*dm1 + a2*dm2

# perturbations along different parameter groups
SEM_perturb_group_names=("dm")  # only one group
SEM_perturb_model_groups=("alpha,beta,phi,xi,eta,rho")
# SEM_perturb_model_tag_groups=("alpha,beta,phi,xi,eta") #,rho")
# SEM_perturb_dmodel_tag_groups=("alpha_dmodel,beta_dmodel,phi_dmodel,xi_dmodel,eta_dmodel") #,rho_dmodel")
# model values are clipped to the range [min,max]
# SEM_perturb_min_values=("-0.15,-0.15,-0.1,-0.1,0.8")
# SEM_perturb_max_values=("0.15,0.15,0.1,0.1,1.2")
# steps along each perturbation group (min,max,ngrids) as in numpy.linspace(min,max,ngrids)
SEM_search_step_sizes=("0,3,31")

# sem_perturb_group_names=("dvpv_vph" "dvsv_vsh" "deta_rho") # three groups
# sem_perturb_model_tag_groups=("vpv,vph" "vsv,vsh" "eta,rho")
# sem_perturb_dmodel_tag_groups=("dvpv_dmodel,dvph_dmodel" "dvsv_dmodel,dvsh_dmodel" "deta_dmodel,drho_dmodel")
# sem_search_group_steps=("0,4,20" "0,4,20" "0,4,20")

#----- estimate inverse of Hessian from kenrel of random model perturbation
# Hess * dm = dKernel ~ Kernel(m+dm) - Kernel(m)
# here, dm is chosen to be a random model perturbation
# diag(Hess) is approximated by water-level inverse of smoothed abs(dKernel)

# SEM_hessian_models=("alpha,beta,phi,xi,eta,rho")
# SEM_Hessian_tag="_invhess"
# random model perturbation
SEM_hessian_perturb_type="abosolute"
SEM_hessian_perturb_amplitude=0.01
# # convert sac to h5 before measure_adj
# SEM_hessian_resample_fs=2
# SEM_hessian_low_pass_freq=0.5
# SEM_hessian_low_pass_order=15
# SEM_hessian_channels=("BXE" "BXN" "BXZ")
# # setup windows use /window in misfit.h5
# SEM_hessian_iter_dir_for_windos=${SEM_base_dir}/stage00.source_dcu/iter04
# smoothing length (on kernel amplitude)
SEM_hessian_smooth_horizontal_length_km=30 # horizontal smoothing length as FWHM
SEM_hessian_smooth_vertical_length_km=15 # vertical smoothing length as FWHM
# waterlevel for inverse hessian diagonals 
SEM_hessian_inverse_nbin=5000
SEM_hessian_inverse_threshold_percentage=0.90

#----- update model

##model_scale_phi_to_xi=1.5
##model_scale_eta_to_xi=2.5
#model_scale_rho_to_beta=0.33
# model_update_min_alpha=-0.15
# model_update_max_alpha=0.15
# model_update_min_beta=-0.15
# model_update_max_beta=0.15
# model_update_min_phi=-0.15
# model_update_max_phi=0.15
# model_update_min_xi=-0.15
# model_update_max_xi=0.15
# model_update_min_eta=0.80
# model_update_max_eta=1.20

##-- preconditioning
## depth weighting (xsem_make_depth_mask)
## the parameters are determined from the depth bins of volume integral
## of kernel amplitudes (xsem_depth_pdf)
#use_depth_mask=1
#depth_stop=10
#depth_pass=500
#depth_mask_type="linear"
##-- L-BFGS (xsem_get_dmodel_lbfgs) 
#use_lbfgs=1
#nstep_lbfgs=1
##-- steepest descent (xsem_get_dmodel_steepest_descent)
#sd_scale_factor=1.0 # kernel scaling factor in steepest-descent
##-- thresholding model update direction (xsem_thresholding)
#use_threshold=1
#threshold_corner=0.9 #corner ratio to threshold kernel amplitudes
#threshold_rmax=0.1 # maximum ratio exceeding corner amplitude
##-- make new model (xem_add_dmodel_***_to_tiso)
##used model tags for model update
##used_kernel_names=mu_kernel
##maximum model relative perturbation ratio
#max_dlnv_allowed=0.03
#force_max_dlnv_allowed=1
##fix density model
#fix_rho=1


##------ hess and kernel
## model names to evaluate Hess*dmodel product
##hess_model_names="random_alpha random_beta"
##hess_model_names="random"
#hess_model_names="perturb_alpha_0.01_grid_5.0deg_200km perturb_beta_0.01_grid_5.0deg_200km"
## smooth the hessian*random 
#hess_smooth_1sigma_h=80 # horizontal smoothing 1 sigma (km)
#hess_smooth_1sigma_v=80 # vertical smoothing 1 sigma (km)
## waterlevel for inverse hessian diagonals 
#hess_inverse_nbin=5000
#hess_inverse_threshold_percentage=0.90


#-----------------------------------------------------------------------#
# Do not edit below                                                     #
#-----------------------------------------------------------------------#
## validate parameters
#if [ ! -d ${init_model_dir} ]
#then
#    echo "[ERROR] initial model directory ${init_model_dir} doesn't exit"
#    exit -1
#fi
#
#if [ ! -d ${prev_mesh_dir} ]
#then
#    echo "[WARNING] ${prev_mesh_dir} doesn't exit, use initial mesh instead"
#    prev_mesh_dir=${init_model_dir}
#fi

#END
